authorName: ttt
experimentName: automl_slt3
trialConcurrency: 4
maxExecDuration: 72h
maxTrialNum: 20
experimentWorkingDirectory: ./nni-experiments
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: CUDA_VISIBLE_DEVICES=0 python3 /hy-tmp/SLT2/trainer/train_pipeline.py  /hy-tmp/SLT2/dataset/processed/ph14_200/
  codeDir: .
  gpuNum: 0
